# Generated by Django 5.2.3 on 2025-06-10 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(max_length=255)),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('current_cycle_hours_used', models.FloatField()),
                ('current_coordinates', models.JSONField(blank=True, null=True)),
                ('pickup_coordinates', models.JSONField(blank=True, null=True)),
                ('dropoff_coordinates', models.JSONField(blank=True, null=True)),
                ('estimated_miles', models.FloatField(blank=True, null=True)),
                ('estimated_drive_hours', models.FloatField(blank=True, null=True)),
                ('total_duty_hours', models.FloatField(blank=True, null=True)),
                ('route_geometry', models.JSONField(blank=True, null=True)),
                ('is_compliant', models.BooleanField(default=False)),
                ('violations', models.JSONField(default=list)),
                ('days_required', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day_number', models.IntegerField()),
                ('timeline_data', models.JSONField()),
                ('total_driving_hours', models.FloatField(default=0)),
                ('total_duty_hours', models.FloatField(default=0)),
                ('total_off_duty_hours', models.FloatField(default=0)),
                ('is_compliant', models.BooleanField(default=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='api.trip')),
            ],
        ),
        migrations.CreateModel(
            name='TripStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_type', models.CharField(choices=[('fuel', 'Fuel Stop'), ('rest', 'Mandatory Rest'), ('pickup', 'Pickup'), ('dropoff', 'Dropoff')], max_length=20)),
                ('coordinates', models.JSONField()),
                ('duration_minutes', models.IntegerField()),
                ('sequence_order', models.IntegerField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='api.trip')),
            ],
        ),
    ]
